# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.2

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            # patch for weirdness in mirrors - https://discuss.circleci.com/t/circleci-failing-when-using-sudo-apt-get-update/29269/9
            sudo sed -i '/jessie-backports/d' /etc/apt/sources.list
            sudo sed -i '/jessie-updates/d' /etc/apt/sources.list
            sudo apt-get -qq update
            sudo apt-get -qq upgrade
            sudo apt-get -qq install build-essential
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip setuptools numpy
            python setup.py install

      - save_cache:
          paths:
            - ./venv

      - run:
          name: run tests
          command: |
            . venv/bin/activate
			python -c 'import pymangle; pymangle.test.test()'

